/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gerenciamento.de.biblioteca;

import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/**
 *
 * @author Ifal
 */
public class TelaCadastrarLivros extends javax.swing.JPanel {

    private static final DateTimeFormatter FORMATO_DATA = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    /**
     * Creates new form TelaCadastrarLivros
     */
    public TelaCadastrarLivros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        Informativo = new javax.swing.JLabel();
        Adicionar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        Nome = new javax.swing.JLabel();
        Autor = new javax.swing.JLabel();
        Ano = new javax.swing.JLabel();
        ISBN = new javax.swing.JLabel();
        DataLabel = new javax.swing.JLabel();
        TextFieldNome = new javax.swing.JTextField();
        TextFieldAutor = new javax.swing.JTextField();
        TextFieldAno = new javax.swing.JTextField();
        TextFieldISBN = new javax.swing.JTextField();
        TextFieldData = new javax.swing.JTextField();
        DicaData = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton3.setText("Voltar");

        Informativo.setText("Cadastro de Livros");

        Adicionar.setText("Adicionar");
        Adicionar.addActionListener(this::AdicionarActionPerformed);

        Voltar.setText("Voltar");
        Voltar.addActionListener(this::VoltarActionPerformed);

        Nome.setText("Nome:");

        Autor.setText("Autor:");

        Ano.setText("Ano:");

        ISBN.setText("ISBN:");

        DataLabel.setText("Data Cadastro:");

        TextFieldData.setToolTipText("Formato: dd/mm/aaaa");

        DicaData.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        DicaData.setText("(dd/mm/aaaa - vazio = hoje)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nome, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ano, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Autor, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ISBN, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DataLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TextFieldNome)
                                        .addComponent(TextFieldAutor)
                                        .addComponent(TextFieldAno)
                                        .addComponent(TextFieldISBN)
                                        .addComponent(TextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(DicaData)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(Adicionar))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Informativo)
                                .addGap(32, 32, 32))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Voltar)))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(Informativo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Autor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ISBN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DicaData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adicionar)
                .addGap(18, 18, 18)
                .addComponent(Voltar)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarActionPerformed
        try {
            String nome = TextFieldNome.getText().trim();
            String autor = TextFieldAutor.getText().trim();
            String anoStr = TextFieldAno.getText().trim();
            String isbnStr = TextFieldISBN.getText().trim();
            String dataStr = TextFieldData.getText().trim();

            if (nome.isEmpty() || autor.isEmpty() || anoStr.isEmpty() || isbnStr.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int ano = Integer.parseInt(anoStr);
            int isbn = Integer.parseInt(isbnStr);

            LocalDate dataCadastro;
            if (dataStr.isEmpty()) {
                dataCadastro = LocalDate.now();
            } else {
                try {
                    dataCadastro = LocalDate.parse(dataStr, FORMATO_DATA);
                } catch (DateTimeParseException e) {
                    JOptionPane.showMessageDialog(this, "Data inválida! Use o formato dd/mm/aaaa.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            Livro novoLivro = new Livro(nome, autor, ano, isbn);
            novoLivro.setDataCadastro(dataCadastro);

            TelaLivros.adicionarLivro(novoLivro);

            TextFieldNome.setText("");
            TextFieldAutor.setText("");
            TextFieldAno.setText("");
            TextFieldISBN.setText("");
            TextFieldData.setText("");

            JOptionPane.showMessageDialog(this, "Livro cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ano e ISBN devem ser números!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AdicionarActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        java.awt.Container parent = this.getParent();
        parent.remove(this);
        TelaLivros telaLivros = new TelaLivros();
        parent.add(telaLivros);
        parent.revalidate();
        parent.repaint();
    }//GEN-LAST:event_VoltarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Adicionar;
    private javax.swing.JLabel Ano;
    private javax.swing.JLabel Autor;
    private javax.swing.JLabel DataLabel;
    private javax.swing.JLabel DicaData;
    private javax.swing.JLabel ISBN;
    private javax.swing.JLabel Informativo;
    private javax.swing.JLabel Nome;
    private javax.swing.JTextField TextFieldAno;
    private javax.swing.JTextField TextFieldAutor;
    private javax.swing.JTextField TextFieldData;
    private javax.swing.JTextField TextFieldISBN;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}