/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gerenciamento.de.biblioteca;

import javax.swing.JOptionPane;

/**
 *
 * @author Ifal
 */
public class TelaCadastrarUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form TelaCadastrarUsuários
     */
    public TelaCadastrarUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Informativo = new javax.swing.JLabel();
        Adicionar = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();
        Nome = new javax.swing.JLabel();
        CPF = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Telefone = new javax.swing.JLabel();
        TextFieldNome = new javax.swing.JTextField();
        TextFieldCPF = new javax.swing.JTextField();
        TextFieldEmail = new javax.swing.JTextField();
        TextFieldTelefone = new javax.swing.JTextField();

        Informativo.setText("Cadastro de Usuários");

        Adicionar.setText("Adicionar");
        Adicionar.addActionListener(this::AdicionarActionPerformed);

        Voltar.setText("Voltar");
        Voltar.addActionListener(this::VoltarActionPerformed);

        Nome.setText("Nome:");

        CPF.setText("CPF:");

        Email.setText("Email:");

        Telefone.setText("Telefone:");

        TextFieldNome.addActionListener(this::TextFieldNomeActionPerformed);
        TextFieldCPF.addActionListener(this::TextFieldCPFActionPerformed);
        TextFieldEmail.addActionListener(this::TextFieldEmailActionPerformed);
        TextFieldTelefone.addActionListener(this::TextFieldTelefoneActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Informativo)
                .addGap(119, 119, 119))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CPF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Telefone, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TextFieldNome)
                                .addComponent(TextFieldCPF)
                                .addComponent(TextFieldEmail)
                                .addComponent(TextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(Adicionar))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Voltar)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(Informativo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Telefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Adicionar)
                .addGap(36, 36, 36)
                .addComponent(Voltar)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void AdicionarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        try {
            // Pega os valores dos campos
            String nome = TextFieldNome.getText().trim();
            String cpf = TextFieldCPF.getText().trim();
            String telefone = TextFieldTelefone.getText().trim();
            String email = TextFieldEmail.getText().trim();
            
            // Valida se os campos não estão vazios
            if (nome.isEmpty() || cpf.isEmpty() || telefone.isEmpty() || email.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                    "Preencha todos os campos!", 
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Valida CPF (apenas números)
            if (!cpf.matches("\\d+")) {
                JOptionPane.showMessageDialog(this, 
                    "CPF deve conter apenas números!", 
                    "Erro", 
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Cria o usuário
            Usuario novoUsuario = new Usuario(nome, cpf, telefone, email);
            
            // Adiciona à lista da TelaUsuarios
            TelaUsuarios.adicionarUsuario(novoUsuario);
            
            // Limpa os campos
            TextFieldNome.setText("");
            TextFieldCPF.setText("");
            TextFieldTelefone.setText("");
            TextFieldEmail.setText("");
            
            // Mensagem de sucesso
            JOptionPane.showMessageDialog(this, 
                "Usuário cadastrado com sucesso!", 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao cadastrar usuário: " + e.getMessage(), 
                "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }                                         

    private void TextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void TextFieldCPFActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void TextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    }                                              

    private void TextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        java.awt.Container parent = this.getParent();

        parent.remove(this);

        TelaUsuarios telaUsuarios = new TelaUsuarios();
        parent.add(telaUsuarios);

        parent.revalidate();
        parent.repaint();
    }                                      

    // Variables declaration - do not modify                     
    private javax.swing.JButton Adicionar;
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Informativo;
    private javax.swing.JLabel Nome;
    private javax.swing.JLabel Telefone;
    private javax.swing.JTextField TextFieldCPF;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.JTextField TextFieldTelefone;
    private javax.swing.JButton Voltar;
    // End of variables declaration                   
}